# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/diarization-stuff',
                'doc_host': 'https://russedavid.github.io',
                'git_url': 'https://github.com/russedavid/diarization-stuff',
                'lib_path': 'diarization_stuff'},
  'syms': {'diarization_stuff.core': {'diarization_stuff.core.foo': ('core.html#foo', 'diarization_stuff/core.py')}}}